apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grade-submission-application-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rajeevbro/grade-submission.git
    targetRevision: main
    path: helm/grade-submission-portal
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grade-submission-application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true